### PR TITLE
Do not store serialization as a state

### PR DESCRIPTION
**Pull request by thiemowmde**
Straight refactoring.

[Bug: T98124](https://phabricator.wikimedia.org/T98124)

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I'm still dubious about this as per comment on https://github.com/wmde/WikibaseInternalSerialization/pull/69. You go from 1 field with a single assignment to it to 0 fields at the cost of adding a dozen parameters. I think that is not a good trade from a code quality perspective. This is not a -2, by all means go ahead if you think this is a good idea.

**Comment by mariushoch** [comment]
+1 makes sense to me, but don't have strong enough feelings to +2

**Comment by thiemowmde** [comment]
@manicki, this is the patch I was talking about. This is the DataValues Serialization component, not DataModel Serialization [we are looking into at the moment](https://github.com/wmde/WikibaseDataModelSerialization/milestone/7).

**Comment by manicki** [comment]
Seems fine to me.
I'd have probably written it the similar way (ie. the way this PR changes this) if I was to write it myself from the scratch.
The issue mentioned in https://github.com/wmde/WikibaseInternalSerialization/pull/69#issuecomment-110007273 that this change increases method complexity is valid. That said I would not have been in favour of this change if the methods that now get $serialization parameter were already parametrized. In this case I think the issue is not that critical. This kind of change has some advantages, and some drawbacks, as said in https://github.com/wmde/WikibaseInternalSerialization/pull/69#issuecomment-110007273. I don't see any of these was bigger in this particular case. I'd be fine with this change.

It is been 2,5 years almost since last activity here, so pinging @mariushoch and @JeroenDeDauw so they can say "No" before I merge this.

**Comment by Ladsgroup** [comment]
I haven't heard of any "No"s since February, thus merging it.

**Pull request merged**
