### PR TITLE
Use Wikibase's CodeSniffer instead of MediaWiki's

### PR DESCRIPTION
**Pull request by thiemowmde**
Changing the array syntax in the same patch because it's not that much here in this code repository.

[Bug: T167436](https://phabricator.wikimedia.org/T167436)

### CODE REVIEW

**Comment by Ladsgroup** [comment]
It has conflict.

**Comment by thiemowmde** [comment]
Manually rebased. I also split #34 off of this patch. You might want to review #34 first.

**Comment by Ladsgroup** [comment]
Now It has another conflict :D

**Comment by thiemowmde** [comment]
Thanks! I rebased this now.

**Pull request merged**
